stages:
  - python

python_typecheck:
    stage: python
    image: python:3.11
    script:
        - python3 -m pip install -r requirements.txt
        - python3 -m pip install flake8 mypy
        - python3 -m pip install -e .
        - python3 -m pip install types-requests
        - mypy .
        - flake8 .
    only:
        changes:
            - "**/*.py"

python_code_formatting:
    stage: python
    image: python:3.10
    script:
        - python3 -m pip install black isort
        - python3 -m black --check .
        - isort -c .
    only:
        changes:
            - "**/*.py"
            - "**/*.pyi"

python_tests:
    stage: python
    image: python:3.11
    script:
        - python3 -m pip install -r requirements.txt
        - python3 -m pip install .
        - cd tests
        - python3 -m pip install -U pytest coverage
        - coverage run --source=. -m pytest -vv --capture=no
        - coverage report
    only:
        changes:
            - "**/*.py"
